var LABEL = {
		ERROR:'出错',
		WARNING:'提醒',
		ALERT:'提示',
		TEXT:{
	        EDIT:[
	            'Edit',
	            '',
	            '编辑'
	        ],
	        MOVE:[
	            '',
	            '',
	            '移动'
	        ],
	        DELETE:[
	            '',
	            '',
	            '删除'
	        ],
	        ROTATE:[
	            '',
	            '',
	            '旋转'
	        ],
	        SCALE:[
	            '',
	            '',
	            '缩放'
	        ],
	        STYLE:[
	            '',
	            '',
	            '样式'
	        ]
	    },
	    SYMBOL:{
	        SLASH:'/'
	    }
}